const API_URL = process.env.REACT_APP_API_URL;

export const API_ENDPOINTS = {
      login: `${API_URL}/login`,
      getArticles: `${API_URL}/articles`,
      getPublishedArticles: `${API_URL}/articles/published`,
      getArticlesfonsej: `${API_URL}/articles/fonsej`,
      getEvents: `${API_URL}/events`,
      editEvents: `${API_URL}/events/edit`,
      deleteEvent: `${API_URL}/events/delete`,
      createEvent: `${API_URL}/events/create`,
      getPublishedEvents: `${API_URL}/events/published`,
      createArticle: `${API_URL}/articles/create`,
      addNewPartner: `${API_URL}/partenaires/create`,
      getPartners: `${API_URL}/partenaires`,
      getMembers: `${API_URL}/members`,
      createDonor: `${API_URL}/donors/create`,
      getDonators: `${API_URL}/donors`,
      createTestimonial: `${API_URL}/testimonial/create`,
      getTestimonial: `${API_URL}/testimonial`,
      getCarouselElement: `${API_URL}/carousel`,
      getYoutubeElement: `${API_URL}/youtube`,
      fonsejSubmit: `${API_URL}/aide/submit`,
      newsletterSubscribe: `${API_URL}/newsletter/create`,
};
